# Site settings
title: Rustom Ichhaporia
description: Rustom Ichhaporia Homepage
baseurl: "home" # the subpath of your site, e.g. /blog
url: "https://rustom-ichhaporia.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rustom Ichhaporia
user_description: I'm Rustom! I'll be writing some more stuff about me here soon. 
user_title: Machine Learning Engineer
email: rustom.ichhaporia@gmail.com
# twitter_username: lorem_ipsum
github_username:  rustom-ichhaporia
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-164610470-1"

exclude: ['package.json', 'src' , 'node_modules']